M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sun 15 Jan 2023 11:35:40 AM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-15T11:35:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.556
%
G90
G05
T1
X201.621Y-37.495
X207.401Y-37.495
T2
X143.043Y-43.404
T3
X127.549Y-36.355
X127.549Y-122.715
X213.909Y-36.355
X213.909Y-122.715
T4
X127.295Y-51.786
X143.043Y-107.031
T0
M30
